version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    volumes:
      - ${DATA_DIRECTORY_PATH}:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /data
