spring:
  application:
    name: musimate-service
  datasource:
    url: ${POSTGRES_DATASOURCE_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  error:
    include-message: always
auth:
  token:
    secret: ${JWT_SECRET}
    refresh-duration-seconds: 86400
    access-duration-seconds: 900