spring:
  application:
    name: Music-Mate Service
  profiles:
    active: dev
  datasource:
    url: ${POSTGRES_DATASOURCE_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
minio:
  url: ${MINIO_URL}
  access:
    username: ${MINIO_USERNAME}
    password: ${MINIO_PASSWORD}
server:
  error:
    include-message: always
auth:
  token:
    secret: ${JWT_SECRET}
    refresh-duration-seconds: 86400
    access-duration-seconds: 900